package com.meta.chat.server.gatewayimpl.database.dataobject;

import java.util.Date;

/**
 * Database Table Remarks:
 *   好友申请记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table friend_apply
 */
public class FriendApplyDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply.friend_apply_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    private Long friendApplyId;

    /**
     * Database Column Remarks:
     *   申请人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply.apply_user_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    private Long applyUserId;

    /**
     * Database Column Remarks:
     *   被申请人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply.be_applied_user_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    private Long beAppliedUserId;

    /**
     * Database Column Remarks:
     *   申请状态，0 已发送，1 已同意，2 已拒绝
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply.status
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply.create_time
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply.update_time
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply.friend_apply_id
     *
     * @return the value of friend_apply.friend_apply_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public Long getFriendApplyId() {
        return friendApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply.friend_apply_id
     *
     * @param friendApplyId the value for friend_apply.friend_apply_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public void setFriendApplyId(Long friendApplyId) {
        this.friendApplyId = friendApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply.apply_user_id
     *
     * @return the value of friend_apply.apply_user_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public Long getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply.apply_user_id
     *
     * @param applyUserId the value for friend_apply.apply_user_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public void setApplyUserId(Long applyUserId) {
        this.applyUserId = applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply.be_applied_user_id
     *
     * @return the value of friend_apply.be_applied_user_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public Long getBeAppliedUserId() {
        return beAppliedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply.be_applied_user_id
     *
     * @param beAppliedUserId the value for friend_apply.be_applied_user_id
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public void setBeAppliedUserId(Long beAppliedUserId) {
        this.beAppliedUserId = beAppliedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply.status
     *
     * @return the value of friend_apply.status
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply.status
     *
     * @param status the value for friend_apply.status
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply.create_time
     *
     * @return the value of friend_apply.create_time
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply.create_time
     *
     * @param createTime the value for friend_apply.create_time
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply.update_time
     *
     * @return the value of friend_apply.update_time
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply.update_time
     *
     * @param updateTime the value for friend_apply.update_time
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}