package com.meta.chat.server.gatewayimpl.database.dataobject;

import java.util.Date;

/**
 * Database Table Remarks:
 *   好友关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table friend_relationship
 */
public class FriendRelationshipBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.friend_relation_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    private Long friendRelationId;

    /**
     * Database Column Remarks:
     *   好友所属人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.user_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   好友id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.friend_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    private Long friendId;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.friend_remark
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    private String friendRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.create_time
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.update_time
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   状态：1可用，2不可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.status
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.friend_relation_id
     *
     * @return the value of friend_relationship.friend_relation_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public Long getFriendRelationId() {
        return friendRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.friend_relation_id
     *
     * @param friendRelationId the value for friend_relationship.friend_relation_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public void setFriendRelationId(Long friendRelationId) {
        this.friendRelationId = friendRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.user_id
     *
     * @return the value of friend_relationship.user_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.user_id
     *
     * @param userId the value for friend_relationship.user_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.friend_id
     *
     * @return the value of friend_relationship.friend_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.friend_id
     *
     * @param friendId the value for friend_relationship.friend_id
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.friend_remark
     *
     * @return the value of friend_relationship.friend_remark
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public String getFriendRemark() {
        return friendRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.friend_remark
     *
     * @param friendRemark the value for friend_relationship.friend_remark
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public void setFriendRemark(String friendRemark) {
        this.friendRemark = friendRemark == null ? null : friendRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.create_time
     *
     * @return the value of friend_relationship.create_time
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.create_time
     *
     * @param createTime the value for friend_relationship.create_time
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.update_time
     *
     * @return the value of friend_relationship.update_time
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.update_time
     *
     * @param updateTime the value for friend_relationship.update_time
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.status
     *
     * @return the value of friend_relationship.status
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.status
     *
     * @param status the value for friend_relationship.status
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}