package com.meta.chat.server.gatewayimpl.database.dataobject;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户登录信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table login_user
 */
public class LongUserDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.id
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.account
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    private String account;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.password
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    private String password;

    /**
     * Database Column Remarks:
     *   用户基础信息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.user_id
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.create_time
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.update_time
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.id
     *
     * @return the value of login_user.id
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.id
     *
     * @param id the value for login_user.id
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.account
     *
     * @return the value of login_user.account
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.account
     *
     * @param account the value for login_user.account
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.password
     *
     * @return the value of login_user.password
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.password
     *
     * @param password the value for login_user.password
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.user_id
     *
     * @return the value of login_user.user_id
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.user_id
     *
     * @param userId the value for login_user.user_id
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.create_time
     *
     * @return the value of login_user.create_time
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.create_time
     *
     * @param createTime the value for login_user.create_time
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.update_time
     *
     * @return the value of login_user.update_time
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.update_time
     *
     * @param updateTime the value for login_user.update_time
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}