package com.meta.chat.server.gatewayimpl.database.dataobject;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户基本信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_base_info
 */
public class UserBaseInfoBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.id
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.nick_name
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.email
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.create_time
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.update_time
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.avatar
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.id
     *
     * @return the value of user_base_info.id
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.id
     *
     * @param id the value for user_base_info.id
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.nick_name
     *
     * @return the value of user_base_info.nick_name
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.nick_name
     *
     * @param nickName the value for user_base_info.nick_name
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.email
     *
     * @return the value of user_base_info.email
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.email
     *
     * @param email the value for user_base_info.email
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.create_time
     *
     * @return the value of user_base_info.create_time
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.create_time
     *
     * @param createTime the value for user_base_info.create_time
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.update_time
     *
     * @return the value of user_base_info.update_time
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.update_time
     *
     * @param updateTime the value for user_base_info.update_time
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.avatar
     *
     * @return the value of user_base_info.avatar
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.avatar
     *
     * @param avatar the value for user_base_info.avatar
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}