package com.meta.chat.server.gatewayimpl.database;

import com.meta.chat.server.gatewayimpl.database.dataobject.FriendApplyDO;

public interface FriendApplyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_apply
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    int deleteByPrimaryKey(Long friendApplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_apply
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    int insert(FriendApplyDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_apply
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    int insertSelective(FriendApplyDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_apply
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    FriendApplyDO selectByPrimaryKey(Long friendApplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_apply
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    int updateByPrimaryKeySelective(FriendApplyDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_apply
     *
     * @mbg.generated Fri May 06 16:40:13 CST 2022
     */
    int updateByPrimaryKey(FriendApplyDO row);
}