package com.meta.chat.server.gatewayimpl.database;

import com.meta.chat.server.gatewayimpl.database.dataobject.FriendRelationshipBO;

public interface FriendRelationshipBOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relationship
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    int deleteByPrimaryKey(Long friendRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relationship
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    int insert(FriendRelationshipBO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relationship
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    int insertSelective(FriendRelationshipBO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relationship
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    FriendRelationshipBO selectByPrimaryKey(Long friendRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relationship
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    int updateByPrimaryKeySelective(FriendRelationshipBO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relationship
     *
     * @mbg.generated Fri May 06 16:41:02 CST 2022
     */
    int updateByPrimaryKey(FriendRelationshipBO row);
}