package com.meta.chat.server.gatewayimpl.database;

import com.meta.chat.server.gatewayimpl.database.dataobject.LongUserDO;

public interface LongUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    int insert(LongUserDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    int insertSelective(LongUserDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    LongUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    int updateByPrimaryKeySelective(LongUserDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Fri May 06 16:37:35 CST 2022
     */
    int updateByPrimaryKey(LongUserDO row);
}