package com.meta.chat.server.gatewayimpl.database;

import com.meta.chat.server.gatewayimpl.database.dataobject.UserBaseInfoBO;

public interface UserBaseInfoBOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    int insert(UserBaseInfoBO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbg.generated Fri May 06 16:38:34 CST 2022
     */
    int insertSelective(UserBaseInfoBO row);
}