#mybatis
mybatis.config-location: classpath:mybatis-config.xml

spring.datasource.initialization-mode: always

spring.datasource.schema: classpath:TableCreationDDL.sql

spring.application.name: meta-chat-server

server.port: 8080

spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

spring.datasource.name: defaultDataSource

spring.datasource.url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC

spring.datasource.username: root
spring.datasource.password: ZHENGguo@2020

mybatis.mapper-locations: classpath:mappers/*xml

mybatis.type-aliases-package: com.meta.chat.server.mybatis.entity


